name: Generate Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      pre_release:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean
      perform_release:
        description: 'Create release'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

env:
  MAKE_PRE_RELEASE: ${{ inputs.pre_release || contains(github.ref, 'pre') }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run package

      - name: Locate package tarball
        id: locate-tarball
        run: |
          ls -la packages/ba63
          echo "tgz_location=$(ls packages/ba63/ba63-*.tgz)" >> $GITHUB_OUTPUT

      - name: Release ba63
        uses: ncipollo/release-action@v1.20.0
        if: ${{ inputs.perform_release || github.event_name == 'push' }}
        with:
          artifacts: ${{ steps.locate-tarball.outputs.tgz_location }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          makeLatest: ${{ !env.MAKE_PRE_RELEASE }}
          prerelease: ${{ env.MAKE_PRE_RELEASE }}
          commit: ${{ github.sha }}
